### ISSUE TITLE
Exclusive Identifier References & Power BI Desktop - M Language Spec Variance

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/query-docs#48]
Per the language specification's discussion on [Identifier references](https://learn.microsoft.com/en-us/powerquery-m/m-spec-basic-concepts#identifier-references):

> It is an error for an exclusive-identifier-reference to refer to an identifier that is currently being initialized if the referenced identifier is defined inside a record-initializer-expression or let-expression.

This rule no longer seems to be followed by Power BI Desktop's version of Power Query, as it successfully resolves the _exclusive_identifier_reference_ of `SumConsecutive(x - 1)` in both of the below expressions:
````
let
  SumConsecutive = (x) => 
    if x <= 0 then 0 
    else x + SumConsecutive(x - 1)
in
  SumConsecutive(3) // returns 6
````

````
[
  SumConsecutive = (x) => 
    if x <= 0 then 0 
    else x + SumConsecutive(x - 1)
][SumConsecutive](3) // returns 6
````

In contrast, the mashup engine that ships with the new Power Query SDK (SDK version 0.2.0) errors on both of the above. In order to get these expressions working with the SDK, the _exclusive-identifier-reference_ of `SumConsecutive(x - 1)` needs to be changed to an _inclusive_identifer_reference_ of `@SumConsecutive(x - 1)`—which is in alignment with what the language specification states.

Is the fact that Power BI Desktop's Power Query accepts these `SumConsecutive(x - 1)`  references as valid a bug? Or, have identifier resolution rules been relaxed, meaning that the language spec. needs a revision?

Thank you!

**Comment by ehrenMSFT** [comment]
I tried both your examples in PBIDesktop (latest internal bits), and I received an error in both cases. Can you share your full M query?

The fact that shared section members (aka queries) can contain self-references without using the @ prefix is probably a bug, but it's one we can't fix at this point due to back-compat. (Thus it's now part of the spec, as of a recent update you made.) The SDK currently flags such references as invalid, but it shouldn't. You could file a bug against the SDK for this issue.

**Comment by bgribaudo** [comment]
HI @ehrenMSFT,

The above examples are given in full. 

I'm using Power BI Desktop Version: 2.110.1161.0 64-bit (October 2022)

![image](https://user-images.githubusercontent.com/857202/202734391-7164b0d7-e23f-4a69-aa03-976212d757c6.png)
![image](https://user-images.githubusercontent.com/857202/202734545-b3a9b246-cbf5-42d3-ad9b-0521a55bd70c.png)

Notice that no syntax errors are reported. When evaluated, both return the results noted.

Interestingly, if I try the same expressions in Excel's Power Query, they both die with an appropriate error.

**Comment by ehrenMSFT** [comment]
I just downloaded and installed the latest October version of PBIDesktop. I don't see syntax errors in the Advanced Editor (which is expected, since this isn't a syntax error). But I do get the error about SumConsecutive when I commit and evaluate the result.

I'm using version 2.110.1161.0 64-bit (October 2022).

**Comment by bgribaudo** [comment]
Hmmm....I uninstalled my existing Power BI Desktop install (which was from the MS Store) and replaced it with the latest directly downloaded setup.exe. I now see the expected behavior, where `SumConsecutive` is not found. 

Interestingly, if I install Power BI Desktop from the Store on a VM, the exclusive `SumConsecutive` also errors, as expected. 

Very strange. Somehow, my (previous) Store-sourced install was acting unexpectantly. 

Thank you for taking a look at this, @ehrenMSFT .
